### ISSUE TITLE
Missing links to examples

### ISSUE THREAD

**Issue by maciejwalkowiak** [tongueroo/lono#32]
This issue is about <http://lono.cloud/examples/> (source file: <https://github.com/tongueroo/lono/blob/master/docs/examples.md>)

Links to sample Lono templates are linking to the very same page.

**Comment by tongueroo** [comment]
@maciejwalkowiak That's my mistake. Started the page and then never got a chance to finish it. Going to comment out for now and put back on my todo. Thanks for reporting it though, totally missed this!

**Comment by tongueroo** [comment]
@maciejwalkowiak Deleted the broken examples and updated the examples page. Only one working example now but it's working and based on the improved `lono import` command. Hope that helps!

**Comment by tongueroo** [comment]
@maciejwalkowiak  Also, if you happen to upgrade lono, version 4 made some structure changes. You should run `lono upgrade4` if you are upgrading from version 3.
