### ISSUE TITLE
May be add suport for tags as for params ?

### ISSUE THREAD

**Issue by opsaaspo** [tongueroo/lono#41]
Hello Tung,

Thanks a lot for add tagging in process of creation or updating stack in release 4.2.7 (options --tags. ).
 
What do you mean if the tags follow the same rules as params (http://lono.cloud/docs/params/)? 
More precisely:
- layering support
- directory structure 
- etc.

PS In my current work I create\update\delete a lot of cloudformation stacks (one template, different zone, ami and etc ). One of the requirements -  each stack has to contain special tags. The list of keys are more or less one for all but values usually are different. If the tags are managed as params (substitute variables, layering and etc.) it will be useful and effective.

Best regards

**Comment by tongueroo** [comment]
Thanks! Fixed

**Comment by tongueroo** [comment]
Something like this?

```
config/tags
├── base.rb
├── development.rb
└── production.rb
```

Unsure really. Might consider pull requests for this.
