### ISSUE TITLE
Example. The value for params contains double dash. Is syntax correct (--ec2-different)?

### ISSUE THREAD

**Issue by opsaaspo** [tongueroo/lono#42]
This issue is about <http://lono.cloud/docs/tutorials/ec2/cfn-create/> (source file: <https://github.com/tongueroo/lono/blob/master/docs/_docs/tutorials/ec2/cfn-create.md>)

Example. The value for params contains double dash. Is syntax correct (--ec2-different)?
Original:
> lono cfn create ec2 --template ec2 --param --ec2-different

Probably:
> lono cfn create ec2 --template ec2 --param ec2-different

**Comment by tongueroo** [comment]
Fixed! Thanks!
